import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
        extend: {
          colors: {
            "on-primary-container": "#9ae8de",
            "surface-container-low": "#f4f4f1",
            "primary": "#00514b",
            "primary-fixed": "#a2f1e6",
            "on-tertiary-fixed": "#0e1e1b",
            "on-primary-fixed": "#00201d",
            "surface-container": "#eeeeeb",
            "on-error": "#ffffff",
            "error-container": "#ffdad6",
            "background": "#f9f9f6",
            "surface-dim": "#dadad7",
            "on-background": "#1a1c1b",
            "secondary": "#895100",
            "surface-container-high": "#e8e8e5",
            "surface": "#f9f9f6",
            "surface-tint": "#0a6a62",
            "tertiary": "#3b4b47",
            "outline": "#6f7977",
            "secondary-fixed": "#ffdcbc",
            "on-primary": "#ffffff",
            "inverse-on-surface": "#f1f1ee",
            "surface-container-highest": "#e2e3e0",
            "surface-variant": "#e2e3e0",
            "surface-bright": "#f9f9f6",
            "on-error-container": "#93000a",
            "tertiary-container": "#52635f",
            "outline-variant": "#bec9c6",
            "surface-container-lowest": "#ffffff",
            "on-primary-fixed-variant": "#00504a",
            "on-tertiary-fixed-variant": "#3a4a46",
            "secondary-container": "#fea12b",
            "on-tertiary": "#ffffff",
            "on-secondary-container": "#693d00",
            "primary-container": "#0d6b63",
            "inverse-surface": "#141d1c",
            "on-secondary": "#ffffff",
            "on-surface": "#1a1c1b",
            "secondary-fixed-dim": "#ffb86c",
            "tertiary-fixed-dim": "#b8cac5",
            "on-secondary-fixed": "#2c1700",
            "on-surface-variant": "#3e4947",
            "error": "#ba1a1a",
            "tertiary-fixed": "#d4e6e1",
            "on-tertiary-container": "#ccded9",
            "inverse-primary": "#86d4ca",
            "primary-fixed-dim": "#86d4ca",
            "on-secondary-fixed-variant": "#683d00"
          },
          borderRadius: {
            "DEFAULT": "0.125rem",
            "lg": "0.25rem",
            "xl": "0.5rem",
            "2xl": "0.875rem",
            "3xl": "1.25rem",
            "full": "9999px"
          },
          spacing: {
            "space-md": "1rem",
            "space-lg": "1.5rem",
            "space-xs": "0.5rem",
            "space-xl": "2.5rem",
            "margin-mobile": "1.25rem",
            "gutter": "1.5rem",
            "space-sm": "0.75rem",
            "margin": "4rem",
            "space-2xs": "0.25rem",
            "space-3xl": "6rem",
            "space-2xl": "4rem",
            "gutter-mobile": "1rem",
            "margin-tablet": "2rem"
          },
          fontFamily: {
            "label-md": ["Manrope", "sans-serif"],
            "metric-number": ["Playfair Display", "serif"],
            "body-md": ["Manrope", "sans-serif"],
            "headline-md": ["Playfair Display", "serif"],
            "display-hero": ["Playfair Display", "serif"],
            "headline-xl": ["Playfair Display", "serif"],
            "body-sm": ["Manrope", "sans-serif"],
            "headline-sm": ["Manrope", "sans-serif"],
            "subheading-editorial": ["Playfair Display", "serif"],
            "label-caps": ["Manrope", "sans-serif"],
            "body-lg": ["Manrope", "sans-serif"],
            "headline-lg": ["Playfair Display", "serif"]
          },
          fontSize: {
            "label-md": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
            "metric-number": ["38px", { "lineHeight": "44px", "fontWeight": "700" }],
            "body-md": ["15px", { "lineHeight": "24px", "fontWeight": "400" }],
            "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
            "display-hero": ["64px", { "lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
            "headline-xl": ["42px", { "lineHeight": "50px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
            "body-sm": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
            "headline-sm": ["18px", { "lineHeight": "26px", "letterSpacing": "0.01em", "fontWeight": "700" }],
            "subheading-editorial": ["21px", { "lineHeight": "32px", "fontWeight": "400" }],
            "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.12em", "fontWeight": "700" }],
            "body-lg": ["17px", { "lineHeight": "28px", "fontWeight": "400" }],
            "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
          }
  }
}
}
export default config
